# Generated by Django 5.1.7 on 2025-04-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_for_anime',
        ),
    ]
